spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true

  datasource:
    url: "jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC"
    username: root
    password: root

#logging.file=D:\\log.txt
