CREATE TABLE public.roles (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                              name VARCHAR(25) NOT NULL,
                              created TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              updated TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
                              status VARCHAR(20) DEFAULT 'ACTIVE' NOT NULL,
                              CONSTRAINT ROLES_PKEY PRIMARY KEY (id),
                              UNIQUE (created),
                              UNIQUE (updated)
);